"""The ladder: each rung must reproduce what it claims, and refuse what it cannot do."""

from __future__ import annotations

import math

import pytest

import blastfrag as bf
from blastfrag.classical import (
    RWS_EXPONENT_DEFAULT,
    cunningham_uniformity_index,
    kuznetsov_x50_m,
    modified_uniformity_index,
    rosin_rammler,
    sieve_grid,
    swebrec,
)
from blastfrag.metrics import score, training_mean
from blastfrag.models import (
    DISCRIMINANT_BOUNDARY,
    GroupDiscriminant,
    Kuznetsov,
    KuzRam,
    NullModel,
    Oracle,
    PublishedRegression,
    RefittedRegression,
    Swebrec,
    discriminant_score,
)
from blastfrag.rockfactor import (
    SITE_ROCK_FACTOR,
    derive_site_rock_factors,
)
from blastfrag.types import Prediction


@pytest.fixture(scope="module")
def train():
    return bf.load_training_corpus()


@pytest.fixture(scope="module")
def holdout():
    return bf.load_holdout(protocol="2012")


# ---------------------------------------------------------------------------------------------
# Controls
# ---------------------------------------------------------------------------------------------

def test_the_oracle_scores_perfectly_which_proves_the_harness(holdout):
    """If the oracle does not score 1.0 the scoring code is broken, not the models."""
    result = score(holdout, Oracle().predict(holdout))
    assert result.r2_identity == pytest.approx(1.0)
    assert result.rmse_m == pytest.approx(0.0, abs=1e-12)


def test_the_null_model_explains_nothing_by_construction(train, holdout):
    result = score(holdout, NullModel().fit(train).predict(holdout))
    # A constant predictor cannot explain variance; on a hold-out whose mean differs slightly from
    # the training mean it comes out marginally negative.
    assert -0.05 < result.r2_identity < 0.0
    assert result.rmse_m == pytest.approx(0.1466, abs=5e-4)


def test_every_arm_sits_between_the_null_and_the_oracle(train, holdout):
    """A rung outside those brackets is reporting something other than skill."""
    floor = score(holdout, NullModel().fit(train).predict(holdout)).rmse_m
    for arm in (Kuznetsov(), PublishedRegression(), RefittedRegression().fit(train)):
        result = score(holdout, arm.predict(holdout))
        assert 0.0 < result.rmse_m < floor, f"{arm.name} did not beat a constant predictor"


# ---------------------------------------------------------------------------------------------
# The classical rung
# ---------------------------------------------------------------------------------------------

def test_the_classical_equation_reproduces_a_published_prediction(train):
    """Rc1's published classical prediction is 0.72 m, and the rock factor was back-solved from it.

    So this is a round trip rather than an independent check, and it verifies the equation's form,
    its units and the geometry beneath it all at once.
    """
    blast = next(b for b in train if b.blast_id == "Rc1")
    pattern = bf.reconstruct_pattern(blast)
    predicted = kuznetsov_x50_m(pattern, SITE_ROCK_FACTOR["Reocin"])
    assert predicted == pytest.approx(0.72, abs=0.005)


def test_the_back_solved_rock_factor_is_near_constant_within_a_site():
    """The evidence that the geometry reconstruction is right.

    An error in burden or bench height would scatter the recovered factor within a site. It does not:
    the widest spread is 3.7 percent, which is what rounding the published predictions to two
    decimals produces.
    """
    derived = derive_site_rock_factors(column="kuzram_2012")
    multi = {site: v for site, v in derived.items() if v[1] > 1}
    assert len(multi) >= 3, "too few multi-blast sites to make this a check"
    for site, (_mean, _n, spread) in multi.items():
        assert spread < 0.05, f"{site}: the recovered factor scatters by {spread:.1%} within a site"


def test_the_pinned_rock_factors_match_their_derivation():
    """The constants are pinned for reproducibility and regenerated by a function; they must agree."""
    derived = derive_site_rock_factors(column="kuzram_2012")
    assert set(derived) == set(SITE_ROCK_FACTOR)
    for site, factor in SITE_ROCK_FACTOR.items():
        assert factor == pytest.approx(derived[site][0], abs=0.005), site


def test_the_two_published_columns_imply_different_rock_factors():
    """Mixing the two papers' columns is a defect, so the difference is pinned rather than averaged.

    The earlier paper's classical predictions are systematically larger, so the factors recovered
    from it are systematically higher.
    """
    a = derive_site_rock_factors(column="kuzram_2012")
    b = derive_site_rock_factors(column="kuzram_2010")
    shared = set(a) & set(b)
    assert len(shared) >= 7
    higher = sum(1 for site in shared if b[site][0] > a[site][0])
    assert higher == len(shared), "the 2010 column should imply a higher factor at every shared site"


def test_every_recovered_rock_factor_is_inside_the_published_valid_range():
    """The literature states 0.8 to 22. A value outside would say the recovery is wrong."""
    assert all(0.8 <= value <= 22.0 for value in SITE_ROCK_FACTOR.values())


def test_the_recovered_factors_track_rock_stiffness_with_one_inversion(train):
    """Stiffer rock needs a larger factor, and the recovered values broadly show it.

    Measured correlation with Young modulus is 0.87 rather than something near one, and the reason
    is a single inversion worth naming: Enusa is the stiffest rock in the corpus at 60 GPa and its
    recovered factor of 10.97 sits BELOW the Reocin carbonates at 45 GPa. Stiffness is not the only
    thing the rock factor carries, and a folded schist is not a massive carbonate. Pinned rather
    than smoothed, because a monotonic claim here would be false.
    """
    modulus = {b.site: b.E_GPa for b in train}
    pairs = [(modulus[site], factor) for site, factor in SITE_ROCK_FACTOR.items() if site in modulus]
    xs = [p[0] for p in pairs]
    ys = [p[1] for p in pairs]
    mean_x, mean_y = sum(xs) / len(xs), sum(ys) / len(ys)
    cov = sum((x - mean_x) * (y - mean_y) for x, y in pairs)
    r = cov / math.sqrt(
        sum((x - mean_x) ** 2 for x in xs) * sum((y - mean_y) ** 2 for y in ys)
    )
    assert r == pytest.approx(0.87, abs=0.02), f"correlation with modulus is {r:.3f}"
    assert SITE_ROCK_FACTOR["Enusa"] < SITE_ROCK_FACTOR["Reocin"], "the recorded inversion is gone"
    assert modulus["Enusa"] > modulus["Reocin"]


def test_the_uniformity_index_lands_in_its_published_range(train):
    """The source states the index is usually between 0.7 and 2.

    This is the unit trap in the equation: the burden is in metres and the diameter in millimetres,
    so the quotient is around 0.027. Reading it as the corpus's dimensionless ratio, which is a
    thousand times larger, sends the index to about -380. This test is what catches that.
    """
    rows = [b for b in train if bf.has_absolute_geometry(b)]
    patterns = [bf.reconstruct_pattern(b) for b in rows]
    indices = [cunningham_uniformity_index(p) for p in patterns]
    assert len(indices) == 91
    assert all(0.15 < n < 2.0 for n in indices), (min(indices), max(indices))

    # Two thirds sit inside the band the source calls usual. The rest are genuinely unusual blasts
    # rather than a broken equation, and this pins WHY: every index below the band comes from a
    # pattern whose charge column is short relative to its bench, because the stemming eats the
    # hole. The index is linear in that ratio, so a short column is exactly what drives it down.
    inside = [n for n in indices if 0.7 <= n <= 2.0]
    assert len(inside) / len(indices) > 0.65
    for pattern, index in zip(patterns, indices):
        if index < 0.7:
            assert pattern.charge_length_m / pattern.bench_height_m < 0.55


def test_the_2005_uniformity_index_is_defined_on_real_patterns(train):
    values = [
        modified_uniformity_index(bf.reconstruct_pattern(b))
        for b in train
        if bf.has_absolute_geometry(b)
    ]
    assert all(0.3 < n < 2.5 for n in values), (min(values), max(values))


def test_the_classical_arm_abstains_where_the_scale_is_unpublished(train):
    """Six rows, and a number on any of them would be an invention."""
    miami = [b for b in train if b.site == "Miami"]
    predictions = Kuznetsov().predict(miami)
    assert len(predictions) == 6
    assert all(p.abstained for p in predictions)
    assert all("publishes no hole diameter" in (p.abstain_reason or "") for p in predictions)


def test_an_abstention_is_counted_not_averaged_away(train):
    """A missing cell and an abstention are different things and must score differently."""
    miami = [b for b in train if b.site == "Miami"]
    result = score(miami, Kuznetsov().predict(miami))
    assert result.n_scored == 0
    assert result.n_abstained == 6


# ---------------------------------------------------------------------------------------------
# Distributions
# ---------------------------------------------------------------------------------------------

def test_rosin_rammler_passes_half_at_the_mean_size():
    """The 0.693 in the exponent is ln 2, which is what makes x50 the fifty-percent size."""
    distribution = rosin_rammler(0.30, 1.2)
    # The tolerance is the sieve grid: passing_at interpolates linearly in log size between
    # grid points, and the default grid steps by about 4 percent.
    assert distribution.passing_at(0.30) == pytest.approx(0.5, abs=1e-4)
    assert distribution.percentile_m(0.5) == pytest.approx(0.30, rel=1e-3)


def test_rosin_rammler_characteristic_size_passes_sixty_three_percent():
    distribution = rosin_rammler(0.30, 1.2)
    characteristic = distribution.detail["characteristic_size_m"]
    assert distribution.passing_at(characteristic) == pytest.approx(1 - 1 / math.e, abs=1e-4)


def test_swebrec_passes_half_at_the_mean_and_everything_at_the_limit():
    distribution = swebrec(0.30, 2.0, 2.0)
    assert distribution.passing_at(0.30) == pytest.approx(0.5, abs=1e-4)
    assert distribution.passing[-1] == pytest.approx(1.0, abs=1e-9)


def test_swebrec_carries_the_counter_example_that_qualifies_it():
    """The source that recommends it also reports a site where the simpler form fitted better."""
    assert "Babaeian" in swebrec(0.3, 2.0, 2.0).detail["caveat"]


def test_a_higher_uniformity_index_narrows_the_distribution():
    narrow = rosin_rammler(0.30, 2.0)
    wide = rosin_rammler(0.30, 0.8)
    span = lambda d: d.percentile_m(0.9) / d.percentile_m(0.1)  # noqa: E731
    assert span(narrow) < span(wide)


def test_the_crush_zone_composition_adds_fines_and_says_its_constants_are_not_published():
    from blastfrag.classical import CrushZoneParameters, crush_zone

    coarse = rosin_rammler(0.30, 1.2)
    composed = crush_zone(0.30, 1.2, CrushZoneParameters(fines_fraction=0.10))
    fine_mesh = 0.005
    assert composed.passing_at(fine_mesh) > coarse.passing_at(fine_mesh)
    assert composed.detail["constants_are_published"] is False


def test_a_distribution_cannot_decrease_with_size():
    """The type refuses it, so a broken model fails at construction rather than on a chart."""
    from blastfrag.types import SizeDistribution

    with pytest.raises(ValueError, match="must not decrease"):
        SizeDistribution(method="broken", sizes_m=[0.1, 0.2], passing=[0.6, 0.4], x50_m=0.15)


def test_the_sieve_grid_is_shared_and_ascending():
    grid = sieve_grid()
    assert grid == sorted(grid)
    assert rosin_rammler(0.3, 1.2).sizes_m == grid
    assert swebrec(0.3, 2.0, 2.0).sizes_m == grid


# ---------------------------------------------------------------------------------------------
# The statistical rung
# ---------------------------------------------------------------------------------------------

def test_the_discriminant_reproduces_every_published_group_membership(train, holdout):
    """Zero errors on all 97 training blasts and all 12 hold-out blasts."""
    for blasts in (train, holdout):
        report = GroupDiscriminant().accuracy(blasts)
        assert report["n_misassigned"] == 0, report["misassigned"]
        assert report["accuracy"] == 1.0


def test_the_two_groups_are_perfectly_separated_by_the_discriminant(train):
    high = [discriminant_score(b) for b in train if b.group == 1]
    low = [discriminant_score(b) for b in train if b.group == 2]
    assert max(low) < min(high), "the groups overlap, so the boundary is not a boundary"
    assert min(high) > DISCRIMINANT_BOUNDARY > max(low)


def test_the_discriminant_abstains_on_size_because_that_is_not_what_it_predicts(train):
    prediction = GroupDiscriminant().predict_one(train[0])
    assert prediction.abstained
    assert prediction.group in (1, 2)


def test_the_published_regression_coefficients_are_not_a_unit_error():
    """The two intercepts differ by a factor of 347 and both return metres.

    That looks wrong and is not: the modulus exponents differ by 0.6 over a range of 9.57 to 60 GPa,
    and the modulus term absorbs the gap. Checked numerically rather than argued.
    """
    from blastfrag.models import PUBLISHED_COEFFICIENTS

    high, low = PUBLISHED_COEFFICIENTS[1], PUBLISHED_COEFFICIENTS[2]
    assert high.intercept / low.intercept == pytest.approx(346.7, rel=0.01)
    # At the boundary of the two groups both equations should return a plausible fragment size.
    for coefficients in (high, low):
        from blastfrag.types import Blast

        probe = Blast(
            blast_id="probe",
            site="probe",
            S_over_B=1.19,
            H_over_B=3.34,
            B_over_D=27.35,
            T_over_B=1.26,
            Pf_kg_m3=0.53,
            XB_m=1.10,
            E_GPa=29.46,
        )
        assert 0.02 < coefficients.predict(probe) < 3.0


def test_the_published_equation_beats_the_numbers_its_own_papers_printed():
    """The finding: applying the published equation correctly outperforms the published table.

    Both source papers print the same two equations. Recomputing them and scoring on the same rows
    gives a materially better result than either paper's own tabulated prediction column, because
    those columns disagree with the equation on several rows.
    """
    arm = PublishedRegression()
    for column, expected_published, expected_ours in (
        ("regression_2010", 0.7467, 0.8537),
        ("regression_2012", 0.7082, 0.8272),
    ):
        rows = [b for b in bf.load_holdout(protocol="union") if b.meta["published"][column] is not None]
        published = score(
            rows,
            [
                Prediction(method="published", blast_id=b.blast_id, x50_m=b.meta["published"][column])
                for b in rows
            ],
        )
        ours = score(rows, arm.predict(rows))
        assert published.r2_identity == pytest.approx(expected_published, abs=5e-4)
        assert ours.r2_identity == pytest.approx(expected_ours, abs=5e-4)
        assert ours.r2_identity > published.r2_identity + 0.10


def test_our_recomputation_agrees_with_the_earlier_paper_where_the_two_disagree():
    """Four rows where the papers differ, and the recomputation lands on the 2010 figure each time."""
    arm = PublishedRegression()
    settled = {"Mr12", "Sm8", "Oz9", "Ad23"}
    for blast in bf.load_holdout(protocol="union"):
        if blast.blast_id not in settled:
            continue
        published = blast.meta["published"]
        ours = round(arm.predict_one(blast).x50_m, 2)
        assert ours == published["regression_2010"], blast.blast_id
        assert ours != published["regression_2012"], blast.blast_id


def test_the_one_row_that_matches_no_published_prediction_is_recorded():
    """Db10: the published equation on its published inputs gives 0.324 m; both papers print 0.16.

    Unresolved, carried with its published inputs. Pinned so it cannot be quietly smoothed away.
    """
    blast = next(b for b in bf.load_holdout(protocol="union") if b.blast_id == "Db10")
    ours = PublishedRegression().predict_one(blast).x50_m
    assert ours == pytest.approx(0.324, abs=0.002)
    assert blast.meta["published"]["regression_2010"] == 0.16
    assert blast.meta["published"]["regression_2012"] == 0.16


def test_refitting_does_not_beat_the_published_coefficients_on_the_holdout(train, holdout):
    """Worth knowing, and slightly against expectation.

    A refit on the same 97 rows generalises marginally WORSE to the published hold-out than the
    coefficients the source authors published, which is a small argument that their fit was not
    overtuned.
    """
    published = score(holdout, PublishedRegression().predict(holdout))
    refitted = score(holdout, RefittedRegression().fit(train).predict(holdout))
    assert refitted.r2_identity < published.r2_identity
    assert refitted.r2_identity > 0.75, "the refit should still be a good model, just not better"


def test_the_refit_refuses_when_a_group_has_too_few_rows(train):
    """Seven exponents from seven rows is interpolation dressed as regression."""
    tiny = [b for b in train if b.group == 1][:5]
    arm = RefittedRegression().fit(tiny)
    prediction = arm.predict_one(train[0])
    assert prediction.abstained
    assert "not contain enough" in (prediction.abstain_reason or "")


# ---------------------------------------------------------------------------------------------
# The interface contract
# ---------------------------------------------------------------------------------------------

def test_a_prediction_carries_a_value_or_a_reason_but_never_both(train):
    with pytest.raises(ValueError, match="never both and never neither"):
        Prediction(method="x", blast_id="b", x50_m=0.3, abstain_reason="also a reason")
    with pytest.raises(ValueError, match="never both and never neither"):
        Prediction(method="x", blast_id="b", x50_m=None)


def test_scoring_refuses_a_missing_row_rather_than_dropping_it(train, holdout):
    """A missing cell is not an abstention, and silently averaging it away is the failure mode."""
    predictions = Kuznetsov().predict(holdout)[:-1]
    with pytest.raises(KeyError, match="not the same as an abstention"):
        score(holdout, predictions)


def test_kuz_ram_returns_a_distribution_where_it_returns_a_size(train):
    blast = next(b for b in train if b.blast_id == "Mg1")
    arm = KuzRam()
    prediction = arm.predict_one(blast)
    distribution = arm.distribution(blast)
    assert distribution is not None
    assert distribution.passing_at(prediction.x50_m) == pytest.approx(0.5, abs=1e-4)


def test_swebrec_and_kuz_ram_share_a_mean_and_differ_in_shape(train):
    blast = next(b for b in train if b.blast_id == "Mg1")
    kuzram = KuzRam().distribution(blast)
    swebrec_dist = Swebrec().distribution(blast)
    assert kuzram.x50_m == pytest.approx(swebrec_dist.x50_m, rel=1e-9)
    fine = 0.01
    assert kuzram.passing_at(fine) != pytest.approx(swebrec_dist.passing_at(fine), rel=1e-3)


def test_the_explosive_strength_exponent_default_is_the_form_the_back_solve_selected():
    assert RWS_EXPONENT_DEFAULT == pytest.approx(-19.0 / 30.0)


def test_training_mean_matches_the_corpus(train):
    assert training_mean(train) == pytest.approx(0.3026, abs=5e-4)
